# Generated by Django 4.2.6 on 2023-11-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0002_remove_participant_age_remove_participant_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournoi',
            name='limite_joueurs',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='participant',
            name='tournoi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournois.tournoi'),
        ),
    ]
