# Generated by Django 4.2.6 on 2023-11-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0003_tournoi_limite_joueurs_alter_participant_tournoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournoi',
            name='limite_joueurs',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
