# Generated by Django 4.2.6 on 2023-11-06 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0004_alter_tournoi_limite_joueurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='tournoi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournois.tournoi'),
        ),
    ]
