# Generated by Django 4.2.6 on 2023-11-06 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0005_alter_participant_tournoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='tournoi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournois.tournoi'),
        ),
    ]
