# Generated by Django 4.2.6 on 2023-11-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0006_alter_participant_tournoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournoi',
            name='limite_joueurs',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
