# Generated by Django 4.2.6 on 2023-11-08 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0008_participant_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='score',
        ),
        migrations.RemoveField(
            model_name='tournoi',
            name='limite_joueurs',
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournois.participant')),
            ],
        ),
    ]
