# Generated by Django 4.2.6 on 2023-11-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0009_remove_participant_score_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
